import "@/styles/globals.css"
import "@/styles/site.css"
import type { Metadata } from "next";
import { OutfitFont } from "./fonts";
import { ModalProvider } from "@/components/Modal/ModalContext";
import { Toaster } from "sonner";
import ChatBot from "@/components/ChatBot/ChatBot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ModalProvider>
      <html lang="en">
        <body className={OutfitFont.className}>
          {children}
          <Toaster richColors position="top-center" />
          <ChatBot />
        </body>
      </html>
    </ModalProvider>
  );
}
